#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Runs all formatting tools"

set -e

mise run format:proto
# Run goimports formatter
mise run format:go

# Add any future Go formatting tools here

exit 0
