#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Run end-to-end tests for the project"

# Run Go acceptance tests
go test -count=1 --tags=acceptance "$@" ./cmd/aigent/...

# Run frontend acceptance tests
cd frontend && npm run test:acceptance
