#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Run JavaScript/TypeScript linting tools"
#MISE depends=["lint:js:prettier-check", "lint:js:eslint"]
