#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Run JavaScript/TypeScript linting tools"

# Run the JavaScript linting tools
mise run lint:js:prettier-check
mise run lint:js:eslint