#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Runs all protobuf formatting tools"

set -e

# Run goimports formatter
mise run format:proto:buf

# Add any future Go formatting tools here

exit 0
