#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Runs all protobuf formatting tools"
#MISE depends=["format:proto:buf"]

set -e

exit 0
