#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Run linting tools for the project"
#MISE depends=["lint:proto", "lint:go", "lint:js", "lint:shellcheck", "lint:reuse"]
