#!/bin/sh
# SPDX-FileCopyrightText: 2025 Mads R. Havmand <mads@v42.dk>
# SPDX-License-Identifier: AGPL-3.0-only
#MISE description="Run Go linting tools"
#MISE depends=["lint:go:goimports", "lint:go:modernize", "lint:go:golangci"]
